pipeline {
    agent any
    stages {
        stage ("BUILD") {
            steps {
                sh "mvn clean install -DskipTests"
            }
        }
        stage ("TEST") {
            steps {
                sh "mvn test"
            }
        }
    }
}
